### ISSUE TITLE
Shows Circluar Spinner in top right corner

### ISSUE THREAD

**Issue by insivika** [apal21/nextjs-progressbar#15]
In additional to the loading bar animation there's a circular spinner in the top right corner of the screen. When inspecting it, I see that it has an id of `nprogress` however I'm unable to hide it via 'display: none`. 
<img width="87" alt="Screen Shot 2020-11-09 at 6 33 07 PM" src="https://user-images.githubusercontent.com/33808429/98620440-2a11c080-22ba-11eb-9d8e-3a074e6d9508.png">

**Comment by apal21** [comment]
Hey @insivika,

This package uses nprogress. So you can do all kinds of modifications it supports.

To hide the spinner, you can do this:

```jsx
<NextNprogress
  options={{ showSpinner: false }}
/>
