### ISSUE TITLE
Show at bottom of screen instead of top

### ISSUE THREAD

**Issue by dancherb** [apal21/nextjs-progressbar#23]
Thanks for this package - is there an easy way to show the bar at the bottom of the screen instead of the top? Changing top:0 to e.g. bottom:3 didn't immediately work.

**Comment by apal21** [comment]
Hey @dancherb, this thing is hardcoded in the CSS [here](https://github.com/apal21/nextjs-progressbar/blob/master/src/index.js#L48). I think this is a very rare use case and I'm not sure whether to create a separate `prop` for this.

Let me know your thoughts. We can discuss on this further

**Comment by dancherb** [comment]
> Hey @dancherb, this thing is hardcoded in the CSS [here](https://github.com/apal21/nextjs-progressbar/blob/master/src/index.js#L48). I think this is a very rare use case and I'm not sure whether to create a separate `prop` for this.
> 
> Let me know your thoughts. We can discuss on this further

Thanks - do you have any idea why simply changing `top:0` to e.g. `bottom:3` doesn't immediately work?

**Comment by apal21** [comment]
Can you share the sample code so that I can tell you what is going on?

**Comment by apal21** [comment]
The other alternative could be, providing the parent element.
If you check the documentation, you can pass `parent` in the configuration.

E.g.
```jsx
<NextNprogress
  options={{ parent: '#loader-parent' }}
/>
```

You can make this parent fixed to the bottom using CSS. Let me know if this helps.
