### ISSUE TITLE
Add showSpinner prop

### ISSUE THREAD

**Issue by max-programming** [apal21/nextjs-progressbar#43]
I couldn't get a showSpinner prop in the props to stop showing the spinner while loading

**Comment by apal21** [comment]
Use this:
```jsx
<NextNprogress
  options={{ showSpinner: false }}
/>
```

Ref: https://github.com/rstacruz/nprogress#configuration

**Comment by max-programming** [comment]
I actually did not get any intellisense in the IDE.

**Comment by max-programming** [comment]
I actually did not get any intellisense in the IDE.

**Comment by max-programming** [comment]
I actually did not get any intellisense in the IDE.

**Comment by max-programming** [comment]
I actually did not get any intellisense in the IDE.

**Comment by max-programming** [comment]
I actually did not get any intellisense in the IDE.
