### ISSUE TITLE
Add Support for Custom Spinners

### ISSUE THREAD

**Issue by Duskfen** [apal21/nextjs-progressbar#66]
Would be great to have support for custom Spinners.
To use like that: 
`<NextNProgress color="black" height="2" > 
<MyCustomSpinner></MyCustomSpinner>
</NextNProgress>`

**Comment by Saracevas** [comment]
This package simply integrates [NProgress](https://github.com/rstacruz/nprogress) with Next.js Router. 

You can do already do what you want by [modifying the CSS of the spinner](https://github.com/rstacruz/nprogress/issues/25#issuecomment-23310286) or by [passing some custom options](https://github.com/apal21/nextjs-progressbar#advanced-config) into the `NextNProgress` to change the template of NProgress.
