### ISSUE TITLE
router.events.emit('routeChangeError'); is not working

### ISSUE THREAD

**Issue by nino-cast** [apal21/nextjs-progressbar#70]
<img width="996" alt="image" src="https://user-images.githubusercontent.com/93901798/155124816-264e5408-b549-46a9-aea2-f197ce0fa536.png">

```
"next": "12.0.10",
"nextjs-progressbar": "^0.0.13",
```

```tsx
// app.tsx

...
<NextNProgress stopDelayMs={0} options={{ showSpinner: false }} />
```

```tsx
// form guard

import { useRouter } from 'next/router';
import { useEffect } from 'react';

export const useFormGuard = (isDirty: boolean) => {
  const router = useRouter();
  const message = 'ok?';

  const pageChangeHandler = () => {
    const answer = window.confirm(message);
    if (!answer) {
      // crash here
      router.events.emit('routeChangeError');
      // throw 'routeChange aborted.';
    }
  };

  const beforeUnloadhandler = (event: BeforeUnloadEvent) => {
    event.preventDefault();
    event.returnValue = message;
  };

  useEffect(() => {
    if (isDirty) {
      router.events.on('routeChangeStart', pageChangeHandler);
      window.addEventListener('beforeunload', beforeUnloadhandler);
      return () => {
        router.events.off('routeChangeStart', pageChangeHandler);
        window.removeEventListener('beforeunload', beforeUnloadhandler);
      };
    }
  }, [isDirty, router]);
};
```

**Comment by apal21** [comment]
Is this related to this package? If so could you please share codesandbox something similar?

**Comment by imranbarbhuiya** [comment]
This isn't related to this package but ik the solution. You are emitting `routeChangeError` without any arguments. If you check 
https://nextjs.org/docs/api-reference/next/router 

you'll find `routeChangeError` emits with 2 args. 

> `routeChangeError(err, url, { shallow }) - Fires when there's an error when changing routes, or a route load is cancelled.

So you need to provide `url` and an object with `shallow` property.

**Comment by nino-cast** [comment]
@apal21 @imranbarbhuiya 
Thank you for your reply. This is [demo](https://codesandbox.io/s/github/nino-cast/next-progressbar-bug-demo/tree/main).

As @imranbarbhuiya points out, I think the cause of the error is the lack of arguments in the handler for routerChangeError.
https://github.com/apal21/nextjs-progressbar/blob/master/src/index.tsx#L73-L77

[The documentation](https://nextjs.org/docs/api-reference/next/router#routerevents) has a shallow as the third error event, but the library handler is trying to get the shallow from the second argument.

**Comment by imranbarbhuiya** [comment]
Using `{shallow}` in `url` is incorrect. But this wont throw any error bc url.shallow is undefined so it'll assume it as false which needs a fix. But in your case this isn't the issue. You aren't passing any parameters when using emit which is causing the error.


You should do like this

```js
router.events.emit('routeChangeError',err, yoururl, {shallow})
```

**Comment by nino-cast** [comment]
@imranbarbhuiya 
thank you for your reply.

I understand that the argument is for listen, not emit. When passing the argument with emit, what kind of content should be specifically passed?

Upon investigation, I could not find an example of passing an argument with emit.

@apal21 
If you know of Sandox where `router.events.emit ('routeChangeError');` works for this library, please let me know.

**Comment by imranbarbhuiya** [comment]
this can help maybe

```ts
const pageChangeHandler = (
    url: string,
    { shallow }: { shallow: boolean }
  ) => {
    if (!shallow) {
      const answer = window.confirm(message);
      if (!answer) {
        router.events.emit('routeChangeError','routeChange aborted.', url, {shallow});
        throw 'routeChange aborted.';
      }
    }
  };
```

**Comment by nino-cast** [comment]
@imranbarbhuiya 
solved. Thank you for your kind answer!
