### ISSUE TITLE
NextNProgress is not defined following the tutorial

### ISSUE THREAD

**Issue by marfin-lab** [apal21/nextjs-progressbar#71]
**_app.js**
`
    // * Components
    // * Natives
    import { NextIntlProvider } from 'next-intl';
    import { useRouter } from 'next/router';
    import { useEffect } from 'react';

    // * Dependencies
    import NextNprogress from 'nextjs-progressbar';
    import * as gtag from '/services/gtag';
    import Analytics from '/components/global/analytics';

    // * Context
    import { AppWrapper } from '/context/state';

    // * CSS
    import 'tailwindcss/tailwind.css';

    // * Render
    export default function MyApp({ Component, pageProps }) {

        const router = useRouter();

        useEffect(() => {
            const handleRouteChange = url => {
                gtag.pageview(url);
            }
            router.events.on('routeChangeComplete', handleRouteChange);
            return () => {
                router.events.off('routeChangeComplete', handleRouteChange)
            }
        }, [router.events]);

        return (
            <>
                <NextIntlProvider messages={pageProps.messages}>
                    <AppWrapper>
                        <NextNProgress color='#3e63ca' />
                        <Component {...pageProps} className='antialiased' />
                        <Analytics />
                    </AppWrapper>
                </NextIntlProvider>
            </>
        )
    }
`

What i'm doing wrong?
![Captura de Tela 2022-02-23 às 11 45 14](https://user-images.githubusercontent.com/58090357/155342545-c9d5fd3f-f8d7-41fb-bcb8-877e1fc0a00c.png)

**Comment by apal21** [comment]
Check the spelling again...
```js
import NextNprogress from 'nextjs-progressbar';
```
This has lowercase `P` and,
```jsx
<NextNProgress color='#3e63ca' />
```
this has uppercase `P`
