### ISSUE TITLE
Expected server HTML to contain a matching <style> in <div>.

### ISSUE THREAD

**Issue by DavidIlie** [apal21/nextjs-progressbar#73]
![image](https://user-images.githubusercontent.com/47594764/162701348-962a9470-37d9-44ae-9e7b-077640db5dc2.png)

**Comment by DavidIlie** [comment]
I can't seem to enable that for Next.js:

```
NODE_OPTIONS=--enable-source-maps yarn dev
```

This is what I am trying and the error looks the same.

**Comment by imranbarbhuiya** [comment]
Ignore my last comment. I forgot I'm talking about nextjs sorry. But in nextjs `development` environment,  by default sourcemap is enabled. So probably u r using an older version of this package. Can u try upgrading your package?

**Comment by DavidIlie** [comment]
I am running the latest version of Next.js

![image](https://user-images.githubusercontent.com/47594764/162725848-a07317a4-3396-46d3-93ce-3c068e91c560.png)

**Comment by imranbarbhuiya** [comment]
> I am running the latest version of Next.js
> 
> ![image](https://user-images.githubusercontent.com/47594764/162725848-a07317a4-3396-46d3-93ce-3c068e91c560.png)

Not next I mean `nextjs-nprogressbar`

**Comment by DavidIlie** [comment]
![image](https://user-images.githubusercontent.com/47594764/162725995-d9966b9d-7e39-418a-ae1a-977722b46f45.png)

I am currently running `nextjs-progressbar` not `nextjs-nprogressbar` is there a difference with that?

**Comment by imranbarbhuiya** [comment]
No sorry typo. If u r using `0.0.14`, you should get the sourcemap. 

Now 
1. Can u run `yarn why nextjs-progressbar` 
2. Can u provide  a minimal repro so I can test this out.

**Comment by imranbarbhuiya** [comment]
> same problem. I just switched from nprogress hoping you fixed it. That code has the same bug.

Can you provide a minimal code sample which is causing the issue? I'm not able to reproduce the issue. That said can u check these 2 issues and solutions seems like your issue is related to these issues
https://github.com/vercel/next.js/issues/8998
https://github.com/vercel/next.js/issues/25489

**Comment by sgehrman** [comment]
as far as I know, I have a typical nextjs typescript project with tailwind.  Are you looking in the Browser's console for the warning?

**Comment by sgehrman** [comment]
Hey, I figured it out.

We hired this hipster coder and he added this hack to our code.

I removed the isServer check and it worked.  I think this was needed for nextjs back in the day?

const App = () => {
      if (isServer) 
          return null;

   return <App></App>
}

const isServer = () => typeof window === 'undefined';
