### ISSUE TITLE
Feature: add ability of hiding spinner

### ISSUE THREAD

**Issue by ksielyov** [apal21/nextjs-progressbar#75]
Now I can`t hide right side spinner

**Comment by imranbarbhuiya** [comment]
You can hide it using
https://github.com/rstacruz/nprogress#showspinner
in https://github.com/apal21/nextjs-progressbar#other-configs

**Comment by smakosh** [comment]
> You can hide it using https://github.com/rstacruz/nprogress#showspinner in https://github.com/apal21/nextjs-progressbar#other-configs

It doesn't hide even if you specify that in the options object
