### ISSUE TITLE
minimize css

### ISSUE THREAD

**Issue by arpecop** [apal21/nextjs-progressbar#79]
could you please min (one liner) the css ... its not optimised currently 
appreciate the great work you did

**Comment by imranbarbhuiya** [comment]
We'll be able to do it easily after https://github.com/apal21/nextjs-progressbar/issues/74 gets implemented.

**Comment by anhtran** [comment]
It's very easy to customize by yourself with emotion.js. Check out my version: https://gist.github.com/anhtran/77cb1bb9db99b534fd69d8f58e8678e8

**Comment by ahmadi-akbar** [comment]
+1

**Comment by gambolputty** [comment]
+1

**Comment by DragoshDX** [comment]
+1
