### ISSUE TITLE
Is there a way to trigger nprogress manually within the hook?

### ISSUE THREAD

**Issue by lamualfa** [apal21/nextjs-progressbar#81]
After the user changes their locale by clicking a locale link, the system will persist the new locale on the user session. So to prevent the app from not giving any feedback to the user while the locale is being persisted, I want to trigger nprogress loading.

Is there a way to trigger nprogress manually within the hook?

![image](https://user-images.githubusercontent.com/39755201/184473541-067f3c5b-be06-428c-9dc2-47b425910d15.png)

**Comment by lamualfa** [comment]
# SOLVED

You can trigger the nprogress manually by installing & import the `nprogress` dependency.

![image](https://user-images.githubusercontent.com/39755201/184474496-3d426c3a-06ba-4838-a699-9fbfa8769d29.png)

**Comment by imranbarbhuiya** [comment]
@apal21 can we re-export `nprogress` from our package so users can use it without reinstalling it?
