### ISSUE TITLE
Version v0.0.15 not published

### ISSUE THREAD

**Issue by groomain** [apal21/nextjs-progressbar#84]
Hi,

I thinks that the version v0.0.15 has not been published on NPM

https://www.npmjs.com/package/nextjs-progressbar

Thanks!

**Comment by groomain** [comment]
Hi, any idea if the v.0.0.15 will be published?

**Comment by raitucarp** [comment]
@apal21 ?

**Comment by apal21** [comment]
https://www.npmjs.com/package/nextjs-progressbar/v/0.0.15
