### ISSUE TITLE
Cannot destructure property 'shallow' of 'undefined' as it is undefined.

### ISSUE THREAD

**Issue by 5ylar** [apal21/nextjs-progressbar#87]
<img width="484" alt="image" src="https://user-images.githubusercontent.com/34544343/206706486-f48b745e-f585-4dca-ad7b-843871174b65.png">

<img width="948" alt="image" src="https://user-images.githubusercontent.com/34544343/206705964-1833b080-0f75-4520-a6b0-c1580cd7f095.png">

https://github.com/apal21/nextjs-progressbar/blob/9ff0eb8ea1dd2d0ef181ac2b64ab312522055627/src/index.tsx#L117

**Comment by imranbarbhuiya** [comment]
You are emitting it incorrectly. Check https://github.com/apal21/nextjs-progressbar/issues/70#issuecomment-1061533686 for fix
